# Generated by Django 6.0.3 on 2026-03-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_message_image_alter_message_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(choices=[('mensahe_ng_pinuno', 'Mensahe ng Pinuno ng PSWDO'), ('department_head', 'Department Head'), ('vision', 'Vision'), ('mission', 'Mission'), ('mandates', 'Mandates'), ('functions', 'Functions'), ('programs_and_services', 'Programs and Services'), ('achievements', 'Achievements'), ('contact_information', 'Contact Information')], max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/content/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Content',
                'verbose_name_plural': 'Homepage Content',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomepageFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='homepage/footer/logo/')),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Footer',
                'verbose_name_plural': 'Homepage Footer',
            },
        ),
        migrations.CreateModel(
            name='HomepageHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='homepage/logo/')),
                ('title', models.CharField(default='Self-Employment Assistance', max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Header',
                'verbose_name_plural': 'Homepage Header',
            },
        ),
    ]
