# Generated by Django 6.0.3 on 2026-03-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
