# Generated by Django 6.0.3 on 2026-03-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('period_type', models.CharField(max_length=20)),
                ('total_loans', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loan_count', models.IntegerField(default=0)),
                ('total_payments', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_count', models.IntegerField(default=0)),
                ('net_cashflow', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'report_summary',
            },
        ),
    ]
