# Generated by Django 6.0.3 on 2026-03-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsummary',
            name='barangay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reportsummary',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reportsummary',
            name='municipality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='reportsummary',
            index=models.Index(fields=['date'], name='report_summ_date_f69e4f_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsummary',
            index=models.Index(fields=['district'], name='report_summ_distric_049f5c_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsummary',
            index=models.Index(fields=['municipality'], name='report_summ_municip_22abe7_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsummary',
            index=models.Index(fields=['barangay'], name='report_summ_baranga_e6c747_idx'),
        ),
    ]
