# Generated by Django 6.0.3 on 2026-03-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_reportsummary_barangay_reportsummary_district_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reportsummary',
            name='report_summ_date_f69e4f_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportsummary',
            name='report_summ_distric_049f5c_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportsummary',
            name='report_summ_municip_22abe7_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportsummary',
            name='report_summ_baranga_e6c747_idx',
        ),
        migrations.RemoveField(
            model_name='reportsummary',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='reportsummary',
            name='district',
        ),
        migrations.RemoveField(
            model_name='reportsummary',
            name='municipality',
        ),
    ]
