# Generated by Django 6.0.3 on 2026-03-18 07:54

import beneficiaries.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'barangay',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'district',
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='beneficiaries.district')),
            ],
            options={
                'db_table': 'municipality',
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id_number', models.AutoField(primary_key=True, serialize=False)),
                ('beneficiary_id', models.CharField(blank=True, editable=False, max_length=7, null=True, unique=True)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced')], max_length=10)),
                ('contact', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('street_house', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Choose', 'Choose'), ('4ps', '4ps'), ('Senior', 'Senior'), ('PWD', 'PWD'), ('Solo Parent', 'Solo Parent'), ('Indigent', 'Indigent')], default='Choose', max_length=50)),
                ('project', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('spouse_name', models.CharField(blank=True, max_length=200, null=True)),
                ('num_of_dependents', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ages_of_dependents', models.CharField(blank=True, help_text="Comma-separated ages, e.g. '3,6,12'", max_length=200, null=True)),
                ('education_level', models.CharField(blank=True, help_text='Elementary/High School/Vocational/College/Others', max_length=50, null=True)),
                ('business_status', models.CharField(blank=True, choices=[('existing', 'Existing Business'), ('starting', 'Starting Business')], max_length=20, null=True)),
                ('type_of_business', models.CharField(blank=True, max_length=200, null=True)),
                ('business_name', models.CharField(blank=True, max_length=200, null=True)),
                ('business_address', models.CharField(blank=True, max_length=255, null=True)),
                ('years_in_operation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nature_of_business', models.CharField(blank=True, choices=[('Retail', 'Retail'), ('Service', 'Service'), ('Food', 'Food'), ('Others', 'Others')], max_length=50, null=True)),
                ('avg_monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('avg_monthly_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('loan_purpose', models.CharField(blank=True, choices=[('Business Expansion', 'Business Expansion'), ('Start-up Capital', 'Start-up Capital'), ('Equipment', 'Equipment'), ('Inventory', 'Inventory'), ('Others', 'Others')], max_length=50, null=True)),
                ('loan_purpose_other', models.CharField(blank=True, max_length=200, null=True)),
                ('owned_assets', models.CharField(blank=True, help_text='Comma-separated: House,Lot,Vehicle,...', max_length=255, null=True)),
                ('other_assets', models.CharField(blank=True, max_length=255, null=True)),
                ('outstanding_loans', models.TextField(blank=True, help_text="If any: source and balance, e.g. 'Sakura Bank - ₱5,000'", null=True)),
                ('is_member_of_org', models.BooleanField(default=False)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('documents_submitted_in_person', models.BooleanField(default=False)),
                ('declaration_signed', models.BooleanField(default=False)),
                ('application_status', models.CharField(default='Pending', max_length=30)),
                ('application_source', models.CharField(choices=[('online', 'Online Application'), ('walkin', 'Walk-in')], default='walkin', max_length=20)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('remarks_admin', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('renewal_count', models.PositiveIntegerField(default=0)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_beneficiaries', to=settings.AUTH_USER_MODEL)),
                ('barangay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beneficiaries.barangay')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beneficiaries.district')),
                ('municipality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beneficiaries.municipality')),
            ],
        ),
        migrations.AddField(
            model_name='barangay',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barangays', to='beneficiaries.municipality'),
        ),
        migrations.CreateModel(
            name='BeneficiaryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('Liham_kahilingan', 'Liham kahilingan sa Punong Lalawigan'), ('Cert_barangay_indigency', 'Certificate of Barangay Indigency'), ('Project_proposal', 'Project Proposal from C/MSWDO'), ('Repayment_schema', 'Repayment Schema from C/MSWDO'), ('Marriage_contract', 'Marriage Contract'), ('Birth_certificate', 'Birth Certificate'), ('Valid_ID', 'Valid ID'), ('Community_Tax', 'Community Tax Certificate (Cedula)'), ('Training_certificate', 'Certificate of training from PCEDO'), ('Other', 'Other')], default='Other', max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to=beneficiaries.models.beneficiary_document_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='beneficiaries.beneficiary')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('beneficiary', 'doc_type'), name='unique_document_per_beneficiary')],
            },
        ),
    ]
