# Generated by Django 6.0.3 on 2026-03-23 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantransaction',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='beneficiaries.beneficiary'),
        ),
    ]
