# Generated by Django 6.0.3 on 2026-03-23 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_loantransaction_beneficiary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loantransaction',
            options={'ordering': ['-loan_date']},
        ),
    ]
