# Generated by Django 6.0.3 on 2026-03-23 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
        ('finance', '0003_alter_loantransaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beneficiaries.barangay'),
        ),
        migrations.AddField(
            model_name='payment',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beneficiaries.district'),
        ),
        migrations.AddField(
            model_name='payment',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beneficiaries.municipality'),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beneficiaries.barangay'),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beneficiaries.district'),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beneficiaries.municipality'),
        ),
    ]
